name: Publish
on:
  push:
    branches:
      - cryogen
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: public
      - name: Clear existing content
        run: rm -rf public/*
      - name: Build site
        run: clj -X:build
      - name: Add changes to Git
        run: git add -A
        working-directory: public
      - name: Add changes to Git
        run: git commit -m 'Cryogen site build'
        working-directory: public
      - name: Push changes to Git
        run: git push origin
