name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Clojure CLI
        uses: DeLaGuardo/setup-clojure@3.0
        with:
          cli: "1.10.1.763"
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Build site
        run: clojure -M:build
      - name: Publish to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
